import pygame

# Game configuration
GAME_WIDTH = 640
GAME_HEIGHT = 360
GAME_TITLE = 'PyOng'
GAME_SCALE = 2
GAME_MAX_FPS = 144

HISCORES_FILENAME = 'hiscores'

# Colors
NOT_SO_WHITE = (244, 241, 221)
NOT_SO_BLACK = (5, 5, 5)
WINDOWS_98 = (0, 128, 128)

# Controls
PLAYER1 = {'up': pygame.K_UP, 'down': pygame.K_DOWN, 'dash': pygame.K_LEFT}
PLAYER2 = {'up': pygame.K_w, 'down': pygame.K_s, 'dash': pygame.K_d}

# Pad
PAD_HEIGHT = 80
PAD_WIDTH = 20
PAD_SPEED = 0.2
PAD_DISTANCE = 10

# Ball
BALL_HEIGHT = 7
BALL_WIDTH = 7
BALL_MIN_START_SPEED = 0.1
BALL_MAX_START_SPEED = 0.3
BALL_SPEED_MULTIPLIER = 1.1
BALL_SPEED_LIMIT = 0.75
BALL_SPEED_TRANSFER = 0.5
BALL_SPEED_TRANSFER_DASH = 0.8

# Math
COLLISION_INTERPOLATION = 200.0

# Game Constants
MULTIPLAYER_LIVES = 25
BALL_DAMAGE = 1
